USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_HEALTHCARE_ETL;
USE DATABASE HEALTHCARE_MIGRATION_DB;

CREATE OR REPLACE STREAM STR_PATIENTS
ON TABLE RAW.PATIENTS;

CREATE OR REPLACE STREAM STR_PROVIDERS
ON TABLE RAW.PROVIDERS;

CREATE OR REPLACE STREAM STR_APPOINTMENTS
ON TABLE RAW.APPOINTMENTS;

SHOW STREAMS;

SELECT *
FROM STR_PATIENTS;