CREATE OR REPLACE DATABASE HEALTHCARE_MIGRATION_DB;

CREATE OR REPLACE SCHEMA HEALTHCARE_MIGRATION_DB.RAW;

CREATE OR REPLACE SCHEMA HEALTHCARE_MIGRATION_DB.STAGING;

CREATE OR REPLACE SCHEMA HEALTHCARE_MIGRATION_DB.MART;

CREATE OR REPLACE SCHEMA HEALTHCARE_MIGRATION_DB.AUDIT;