USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_HEALTHCARE_ETL;
USE DATABASE HEALTHCARE_MIGRATION_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE STG_S3_PATIENTS
URL = 's3://jonathan-healthcare-snowflake-migration-dev/raw/patients/'
STORAGE_INTEGRATION = S3_HEALTHCARE_INTEGRATION
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE STAGE STG_S3_PROVIDERS
URL = 's3://jonathan-healthcare-snowflake-migration-dev/raw/providers/'
STORAGE_INTEGRATION = S3_HEALTHCARE_INTEGRATION
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE STAGE STG_S3_APPOINTMENTS
URL = 's3://jonathan-healthcare-snowflake-migration-dev/raw/appointments/'
STORAGE_INTEGRATION = S3_HEALTHCARE_INTEGRATION
FILE_FORMAT = CSV_FORMAT;

SHOW STAGES IN SCHEMA HEALTHCARE_MIGRATION_DB.RAW;