USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_HEALTHCARE_ETL;
USE DATABASE HEALTHCARE_MIGRATION_DB;
USE SCHEMA RAW;

SELECT 'PATIENTS' AS table_name, COUNT(*) AS snowflake_row_count FROM PATIENTS
UNION ALL
SELECT 'PROVIDERS', COUNT(*) FROM PROVIDERS
UNION ALL
SELECT 'APPOINTMENTS', COUNT(*) FROM APPOINTMENTS;